services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcribe_api
    ports:
      - "5000:5000"
    environment:
      - API_KEY=${API_KEY}
      - HOST=${HOST}
      - PORT=${PORT}
      - FLASK_APP=app.py